### ISSUE TITLE
The 'InvokeCoreAsync' method cannot be called if the connection is not active

### ISSUE THREAD

**Issue by dmitry-pavlov** [berhir/SignalR.Modules#6]
I am getting the following error on any user action (like Counter click, etc): 

`The 'InvokeCoreAsync' method cannot be called if the connection is not active`

Any thoughts about what I am missing, @berhir ? 
Are there any nuances I should keep in mind when running Blazor samples on local machine? 

P.S. I would suggest to consider adding the steps to run the Blazor sample projects to the README. Maybe also - how to add a simple change to one of the hubs to see the generation in action. 

![image](https://user-images.githubusercontent.com/1560778/143904099-6df2c2f4-511f-4557-81e6-7ceb191cb570.png)

**Comment by berhir** [comment]
Hi @dmitry-pavlov, are you still seeing this error? I just tried it again and I don't see this problem.
To run the sample, select the `BlazorSignalR.Server` as startup project and start it.

From the screenshot it seems you are using IIS Express. Can you try to run it with Kestrel?

**Comment by dmitry-pavlov** [comment]
Ok @berhir , I have set `BlazorSignalR.Server` as a startup project and ran as `Project`. 

When I go to let say `Counter` page I see this in the console log: 

```
 Microsoft.AspNetCore.SignalR.HubConnectionHandler[1]
      Error when dispatching 'OnConnectedAsync' on hub.
      System.InvalidOperationException: Unable to resolve service for type 'Microsoft.Extensions.Logging.ILogger' while attempting to activate 'BlazorSignalR.Server.Hubs.MainHub'.
         at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
         at lambda_method43(Closure , IServiceProvider , Object[] )
         at Microsoft.AspNetCore.SignalR.Internal.DefaultHubActivator`1.Create()
         at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.OnConnectedAsync(HubConnectionContext connection)
         at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.OnConnectedAsync(HubConnectionContext connection)
         at Microsoft.AspNetCore.SignalR.HubConnectionHandler`1.RunHubAsync(HubConnectionContext connection)
```

And when I click `Click me` button I see `The 'InvokeCoreAsync' method cannot be called if the connection is not active` in the browser dev console: 
![RIQBgUT40I](https://user-images.githubusercontent.com/1560778/146199100-262bd102-6a0f-4df2-ae10-ad1c6fe0f2e2.png)

Any thoughts?
